# NumPy

1. **Import NumPy**


2. **Create NumPy Arrays**

   2.1. `array`
   
   2.2. `ones`
   
   2.3. `zeros`
   
   2.4. `linspace`
   

3. **Basic Array Operations**

   3.1. Arithmetic operations
   
   3.2. Indexing and slicing
   
   3.3. Aggregation functions
   

4. **Array Manipulation**

   4.1. Reshaping arrays
   
   4.2. Stacking arrays
   
   4.3. Transposing arrays
   

5. **Linear Algebra Operations**

   5.1. Matrix multiplication
   
   5.2. Eigenvalues and eigenvectors
   

6. **Random Number Generation**

   6.1. Generate random integers
   
   6.2. Generate random samples from a normal distribution
   

7. **File Input/Output**

   7.1. Save and load arrays from/to a text file



### Tasks:

1. Create a NumPy array filled with integers from 0 to 9.
2. Calculate the sum of all elements in a NumPy array.
3. Reshape a 1D NumPy array into a 2D array with 2 rows and 3 columns.
4. Generate a random NumPy array of shape (3, 3) containing values between 0 and 1.
5. Find the maximum value in a NumPy array.
6. Compute the mean of values in a NumPy array.
7. Access the second element in the third row of a NumPy array.
8. Create a NumPy array with the first 10 even numbers.
9. Stack two NumPy arrays vertically.
10. Multiply each element of a NumPy array by 2.
11. Perform element-wise multiplication between two NumPy arrays of shape (3, 3).
12. Compute the dot product of two NumPy arrays representing matrices.
13. Reshape a 2D NumPy array into a 1D array.
14. Generate a random NumPy array of shape (4, 4) from a normal distribution.
15. Compute the eigenvalues and eigenvectors of a symmetric matrix using NumPy.
16. Implement a function to compute the determinant of a square matrix using NumPy.
17. Solve a system of linear equations using NumPy.
18. Perform matrix factorization using Singular Value Decomposition (SVD) with NumPy.
19. Implement a function to calculate the cross-product of two 3D vectors using NumPy.
20. Generate a NumPy masked array where elements are masked based on a condition.


In [72]:
1e7

10000000.0

In [74]:
import time

In [79]:
 

start_time  = time.perf_counter()

ops = 100000

for i in range(ops):
    a = 3
    b = 5
    c = a+b
    

end_time  = time.perf_counter()

time_taken = end_time - start_time

pre_sec = time_taken/ops

print(time_taken,pre_sec)


0.017570911906659603 1.7570911906659604e-07


In [80]:
import numpy 

In [81]:
from numpy import *

In [84]:
from numpy import abs, sum, min

In [85]:
from numpy import (abs,
                  sum,
                  min)

In [86]:
import numpy as np

In [87]:
lst = [1,2,3]
lst

[1, 2, 3]

In [88]:
type(lst)

list

In [89]:
arr1 = np.array([1,2,3])

In [90]:
type(arr1)

numpy.ndarray

In [91]:
lst*2

[1, 2, 3, 1, 2, 3]

In [92]:
arr1*2

array([2, 4, 6])

In [95]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [96]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [97]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [100]:
list(range(1,30))

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [107]:
arr1 = np.arange(1,10, dtype="int32")
arr2 = np.arange(1,10)
print(f"{arr1= },\n {arr2= }")

arr1= array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32),
 arr2= array([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [103]:
arr1 + arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [114]:
arr3 = np.arange(1,51).reshape(2,25)

In [122]:
arr3

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [128]:
arr3[0][6]

7

In [127]:
arr3[:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [6]:
#import functools

#@functools.lru_cache(maxsize=None)
def factors(n):
    return sum([i for i in range(1,n) if n%i ==0])

In [5]:
[[i,j] for i in range(1, 10000) for j in range(i+1 ,10000) if factors(i) == j and factors(j)==i]

[[220, 284], [1184, 1210], [2620, 2924], [5020, 5564], [6232, 6368]]

In [135]:
a = 10000*10000
b = a*a
total = 2*b
print(f"{total:_}")

20_000_000_000_000_000


In [136]:
ns = total/1e9
sec = ns/60
mins = sec/60
hours = mins/24
days = hours/365

In [137]:
days

0.6341958396752918

In [138]:
hours

231.4814814814815

In [8]:
arr12 =np.array([1,2,3]) 
arr8 =np.array([4,5,6])

np.hstack((arr12,arr8))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([1, 2, 3, 4, 5, 6])

In [13]:
mat = np.vstack(((arr12,arr8)))
mat

<IPython.core.display.Javascript object>

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.transpose(mat)

<IPython.core.display.Javascript object>

array([[1, 4],
       [2, 5],
       [3, 6]])

In [18]:
mat1 = np.array([[1, 4],
       [2, 5],
       [3, 6]])

mat2 = np.transpose(np.array([[1, 2],
       [3, 4],
       [5, 6]]))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [21]:
mat3 = np.dot(mat1,mat2)

<IPython.core.display.Javascript object>

In [22]:
eigenvalue , eigenvector = np.linalg.eig(mat3)

<IPython.core.display.Javascript object>

In [23]:
print(f"{eigenvalue= }|{eigenvector=}")

eigenvalue= array([ 8.55793377e+01,  4.20662288e-01, -2.65877698e-15])|eigenvector=array([[-0.4111447 , -0.88016077,  0.40824829],
       [-0.56374526, -0.23342163, -0.81649658],
       [-0.71634581,  0.4133175 ,  0.40824829]])


In [24]:
np.linalg.det(mat3)

<IPython.core.display.Javascript object>

-1.0125233984581384e-14

In [25]:
np.linalg.svd(mat3)

<IPython.core.display.Javascript object>

(array([[-0.41037278,  0.81543088,  0.40824829],
        [-0.56362703,  0.12513157, -0.81649658],
        [-0.71688127, -0.56516774,  0.40824829]]),
 array([8.72801803e+01, 4.12464776e-01, 1.86197084e-15]),
 array([[-0.24301162, -0.52828107, -0.81355052],
        [ 0.87993107,  0.23292153, -0.41408801],
        [ 0.40824829, -0.81649658,  0.40824829]]))

In [27]:
help(np.linalg)

<IPython.core.display.Javascript object>

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    ``numpy.linalg``
    
    The NumPy linear algebra functions rely on BLAS and LAPACK to provide efficient
    low level implementations of standard linear algebra algorithms. Those
    libraries may be provided by NumPy itself using C versions of a subset of their
    reference implementations but, when possible, highly optimized libraries that
    take advantage of specialized processor functionality are preferred. Examples
    of such libraries are OpenBLAS, MKL (TM), and ATLAS. Because those libraries
    are multithreaded and processor dependent, environmental variables and external
    packages such as threadpoolctl may be needed to control the number of threads
    or specify the processor architecture.
    
    - OpenBLAS: https://www.openblas.net/
    - threadpoolctl: https://github.com/joblib/threadpoolctl
    
    Please note that the most-used linear algebra functions in NumPy are present in
    t

In [30]:
np.random.randint((10,2))

<IPython.core.display.Javascript object>

array([7, 0])

In [36]:
np.random.random(20)

<IPython.core.display.Javascript object>

array([0.19108953, 0.26932941, 0.63370769, 0.97496562, 0.89069984,
       0.25443685, 0.43405657, 0.13010547, 0.31400754, 0.93099584,
       0.24600551, 0.38519238, 0.54379974, 0.58854498, 0.68371707,
       0.03655757, 0.05587474, 0.99017209, 0.50309625, 0.61346942])

In [40]:
normal_distro = np.random.standard_normal((10,20))

<IPython.core.display.Javascript object>

In [41]:
np.savetxt("sample.txt",normal_distro)

<IPython.core.display.Javascript object>

In [42]:
!ls

'Advanced Python.ipynb'  'Mini Projects.ipynb'		    sample.ipynb
 Assignment.ipynb	  NUmpy.ipynb			    sample.txt
 Foundation.ipynb	 'Python Code Optimization.ipynb'   sa.txt
 List_Assignment.ipynb	  README.md			    Untitled.ipynb


In [43]:
!cat sample.txt

1.114265689783299901e-01 -1.482974636913264144e+00 -1.508312924831621271e-01 6.865916719390482426e-01 1.191890222702813307e-01 -7.620696078346405056e-01 -3.890599509879427709e-01 -5.549354155874471894e-01 -6.892605299078295999e-01 2.010822807440753923e+00 -1.664478318763778830e+00 1.905433457021689314e+00 -8.345384989202966342e-01 4.208004021846892262e-02 1.130698639372583969e+00 -2.163536371218267862e-01 1.651012747107984291e+00 -1.541666573080947011e-01 -3.603534198304806369e-01 -2.075185154202546123e+00
6.602532062206790953e-02 9.025666757013545149e-01 -9.979842845787502137e-01 4.085855457359717779e-01 -3.407382432096752178e-01 2.045997352231625488e-01 1.698227335262894711e+00 5.202292274923487891e-01 -2.318621698328170999e-01 -2.835851522437943806e-01 1.708407382762808790e-01 -9.338055804107903146e-02 6.303095755178654835e-01 -4.450006145536208879e-01 -7.326937941137083854e-01 8.495487261143240820e-01 1.118674154953121613e+00 7.146776865036338355e-01 -2.571539627918603799e+00 1.323

In [46]:
x=np.loadtxt("sample.txt")

<IPython.core.display.Javascript object>

In [47]:
x

array([[ 1.11426569e-01, -1.48297464e+00, -1.50831292e-01,
         6.86591672e-01,  1.19189022e-01, -7.62069608e-01,
        -3.89059951e-01, -5.54935416e-01, -6.89260530e-01,
         2.01082281e+00, -1.66447832e+00,  1.90543346e+00,
        -8.34538499e-01,  4.20800402e-02,  1.13069864e+00,
        -2.16353637e-01,  1.65101275e+00, -1.54166657e-01,
        -3.60353420e-01, -2.07518515e+00],
       [ 6.60253206e-02,  9.02566676e-01, -9.97984285e-01,
         4.08585546e-01, -3.40738243e-01,  2.04599735e-01,
         1.69822734e+00,  5.20229227e-01, -2.31862170e-01,
        -2.83585152e-01,  1.70840738e-01, -9.33805580e-02,
         6.30309576e-01, -4.45000615e-01, -7.32693794e-01,
         8.49548726e-01,  1.11867415e+00,  7.14677687e-01,
        -2.57153963e+00,  1.32369773e+00],
       [ 3.27405560e-01,  3.09201282e-01,  9.73351572e-01,
        -1.46626616e+00,  2.07128992e+00, -9.16026584e-01,
         2.69911437e+00, -1.86684513e+00,  1.06533394e-01,
         1.49077778e-01,  2.9

In [48]:
arr = np.arange(0,10)
arr

<IPython.core.display.Javascript object>

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.sum(arr)

<IPython.core.display.Javascript object>

45

In [50]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
np.random.random(6)

<IPython.core.display.Javascript object>

array([0.78155153, 0.52440754, 0.10924007, 0.71738356, 0.11377239,
       0.16953499])

In [54]:
help(np.resize)

<IPython.core.display.Javascript object>

Help on function resize in module numpy:

resize(a, new_shape)
    Return a new array with the specified shape.
    
    If the new array is larger than the original array, then the new
    array is filled with repeated copies of `a`.  Note that this behavior
    is different from a.resize(new_shape) which fills with zeros instead
    of repeated copies of `a`.
    
    Parameters
    ----------
    a : array_like
        Array to be resized.
    
    new_shape : int or tuple of int
        Shape of resized array.
    
    Returns
    -------
    reshaped_array : ndarray
        The new array is formed from the data in the old array, repeated
        if necessary to fill out the required number of elements.  The
        data are repeated in the order that they are stored in memory.
    
    See Also
    --------
    ndarray.resize : resize an array in-place.
    
    Notes
    -----
    i.e. it does not apply interpolation/extrapolation.
    It fills the return array with the required 